#pragma once

#include <string>
#include "Attributes.h"
#include "Item.h"

/// \brief Armor Class to be generated by the ItemFactory
class Armor : public Item
{
  public:
	    
   /// \equips the armor
   ///
   /// Detailed Description
   /// \return bool if the item was successfully used 
   bool use();

  private:
   std::string name;
   std::string description;
   Attributes stats;
};
